;;;----------------------------------------------------------------------------------
;;; Generated by protoc-gen-clojure.  DO NOT EDIT
;;;
;;; GRPC protojure.test.flowcontrol.FlowControl Client Implementation
;;;----------------------------------------------------------------------------------
(ns protojure.test.flowcontrol.FlowControl.client
  (:require [protojure.test.flowcontrol :refer :all]
            [clojure.core.async :as async]
            [protojure.grpc.client.utils :refer [send-unary-params invoke-unary]]
            [promesa.core :as p]
            [protojure.grpc.client.api :as grpc]))

;-----------------------------------------------------------------------------
; GRPC Client Implementation
;-----------------------------------------------------------------------------

(defn StreamOut
  [client params reply]
  (let [input (async/chan 1)
        desc {:service "protojure.test.flowcontrol.FlowControl"
              :method  "StreamOut"
              :input   {:f protojure.test.flowcontrol/new-StreamOutRequest :ch input}
              :output  {:f protojure.test.flowcontrol/pb->Payload :ch reply}}]
    (-> (send-unary-params input params)
        (p/then (fn [_] (grpc/invoke client desc))))))

