;;;----------------------------------------------------------------------------------
;;; Generated by protoc-gen-clojure.  DO NOT EDIT
;;;
;;; GRPC protojure.test.flowcontrol.FlowControl Service Implementation
;;;----------------------------------------------------------------------------------
(ns protojure.test.flowcontrol.FlowControl.server
  (:require [protojure.test.flowcontrol :refer :all]
))

;-----------------------------------------------------------------------------
; GRPC FlowControl
;-----------------------------------------------------------------------------
(defprotocol Service
  (StreamOut [this param]))

(defn- StreamOut-dispatch
  [ctx request]
  (StreamOut ctx request))

(def ^:const rpc-metadata
  [{:pkg "protojure.test.flowcontrol" :service "FlowControl" :method "StreamOut" :method-fn StreamOut-dispatch :server-streaming true :client-streaming false :input pb->StreamOutRequest :output new-Payload}])
