;;;----------------------------------------------------------------------------------
;;; Generated by protoc-gen-clojure.  DO NOT EDIT
;;;
;;; GRPC protojure.test.metadata.Metadata Client Implementation
;;;----------------------------------------------------------------------------------
(ns protojure.test.metadata.Metadata.client
  (:require [protojure.test.metadata :refer :all]
            [com.google.protobuf :as com.google.protobuf]
            [clojure.core.async :as async]
            [protojure.grpc.client.utils :refer [send-unary-params invoke-unary]]
            [promesa.core :as p]
            [protojure.grpc.client.api :as grpc]))

;-----------------------------------------------------------------------------
; GRPC Client Implementation
;-----------------------------------------------------------------------------

(defn HelloAuth
  [client params]
  (let [input (async/chan 1)
        output (async/chan 1)
        desc {:service "protojure.test.metadata.Metadata"
              :method  "HelloAuth"
              :input   {:f com.google.protobuf/new-Empty :ch input}
              :output  {:f protojure.test.metadata/pb->Response :ch output}}]
    (-> (send-unary-params input params)
        (p/then (fn [_] (invoke-unary client desc output))))))

