;;;----------------------------------------------------------------------------------
;;; Generated by protoc-gen-clojure.  DO NOT EDIT
;;;
;;; GRPC protojure.test.metadata.Metadata Service Implementation
;;;----------------------------------------------------------------------------------
(ns protojure.test.metadata.Metadata.server
  (:require [protojure.test.metadata :refer :all]
            [com.google.protobuf :as com.google.protobuf]))

;-----------------------------------------------------------------------------
; GRPC Metadata
;-----------------------------------------------------------------------------
(defprotocol Service
  (HelloAuth [this param]))

(defn- HelloAuth-dispatch
  [ctx request]
  (HelloAuth ctx request))

(def ^:const rpc-metadata
  [{:pkg "protojure.test.metadata" :service "Metadata" :method "HelloAuth" :method-fn HelloAuth-dispatch :server-streaming false :client-streaming false :input com.google.protobuf/pb->Empty :output new-Response}])
