;;;----------------------------------------------------------------------------------
;;; Generated by protoc-gen-clojure.  DO NOT EDIT
;;;
;;; Message Implementation of package protojure.test.grpc
;;;----------------------------------------------------------------------------------
(ns protojure.test.grpc
  (:require [protojure.protobuf.protocol :as pb]
            [protojure.protobuf.serdes.core :as serdes.core]
            [protojure.protobuf.serdes.complex :as serdes.complex]
            [protojure.protobuf.serdes.utils :refer [tag-map]]
            [protojure.protobuf.serdes.stream :as serdes.stream]
            [com.google.protobuf :as com.google.protobuf]
            [clojure.set :as set]
            [clojure.spec.alpha :as s]))

;;----------------------------------------------------------------------------------
;;----------------------------------------------------------------------------------
;; Forward declarations
;;----------------------------------------------------------------------------------
;;----------------------------------------------------------------------------------

(declare cis->CloseDetectRequest)
(declare ecis->CloseDetectRequest)
(declare new-CloseDetectRequest)
(declare cis->FlowControlRequest)
(declare ecis->FlowControlRequest)
(declare new-FlowControlRequest)
(declare cis->FlowControlPayload)
(declare ecis->FlowControlPayload)
(declare new-FlowControlPayload)
(declare cis->MetadataResponse)
(declare ecis->MetadataResponse)
(declare new-MetadataResponse)


;;----------------------------------------------------------------------------------
;;----------------------------------------------------------------------------------
;; Message Implementations
;;----------------------------------------------------------------------------------
;;----------------------------------------------------------------------------------

;-----------------------------------------------------------------------------
; CloseDetectRequest
;-----------------------------------------------------------------------------
(defrecord CloseDetectRequest-record [id]
  pb/Writer
  (serialize [this os]
    (serdes.core/write-String 1  {:optimize true} (:id this) os))
  pb/TypeReflection
  (gettype [this]
    "protojure.test.grpc.CloseDetectRequest"))

(s/def :protojure.test.grpc.CloseDetectRequest/id string?)
(s/def ::CloseDetectRequest-spec (s/keys :opt-un [:protojure.test.grpc.CloseDetectRequest/id ]))
(def CloseDetectRequest-defaults {:id "" })

(defn cis->CloseDetectRequest
  "CodedInputStream to CloseDetectRequest"
  [is]
  (->> (tag-map CloseDetectRequest-defaults
         (fn [tag index]
             (case index
               1 [:id (serdes.core/cis->String is)]

               [index (serdes.core/cis->undefined tag is)]))
         is)
        (map->CloseDetectRequest-record)))

(defn ecis->CloseDetectRequest
  "Embedded CodedInputStream to CloseDetectRequest"
  [is]
  (serdes.core/cis->embedded cis->CloseDetectRequest is))

(defn new-CloseDetectRequest
  "Creates a new instance from a map, similar to map->CloseDetectRequest except that
  it properly accounts for nested messages, when applicable.
  "
  [init]
  {:pre [(if (s/valid? ::CloseDetectRequest-spec init) true (throw (ex-info "Invalid input" (s/explain-data ::CloseDetectRequest-spec init))))]}
  (-> (merge CloseDetectRequest-defaults init)
      (map->CloseDetectRequest-record)))

(defn pb->CloseDetectRequest
  "Protobuf to CloseDetectRequest"
  [input]
  (cis->CloseDetectRequest (serdes.stream/new-cis input)))

(def ^:protojure.protobuf.any/record CloseDetectRequest-meta {:type "protojure.test.grpc.CloseDetectRequest" :decoder pb->CloseDetectRequest})

;-----------------------------------------------------------------------------
; FlowControlRequest
;-----------------------------------------------------------------------------
(defrecord FlowControlRequest-record [count payload-size]
  pb/Writer
  (serialize [this os]
    (serdes.core/write-Int32 1  {:optimize true} (:count this) os)
    (serdes.core/write-Int32 2  {:optimize true} (:payload-size this) os))
  pb/TypeReflection
  (gettype [this]
    "protojure.test.grpc.FlowControlRequest"))

(s/def :protojure.test.grpc.FlowControlRequest/count int?)
(s/def :protojure.test.grpc.FlowControlRequest/payload-size int?)
(s/def ::FlowControlRequest-spec (s/keys :opt-un [:protojure.test.grpc.FlowControlRequest/count :protojure.test.grpc.FlowControlRequest/payload-size ]))
(def FlowControlRequest-defaults {:count 0 :payload-size 0 })

(defn cis->FlowControlRequest
  "CodedInputStream to FlowControlRequest"
  [is]
  (->> (tag-map FlowControlRequest-defaults
         (fn [tag index]
             (case index
               1 [:count (serdes.core/cis->Int32 is)]
               2 [:payload-size (serdes.core/cis->Int32 is)]

               [index (serdes.core/cis->undefined tag is)]))
         is)
        (map->FlowControlRequest-record)))

(defn ecis->FlowControlRequest
  "Embedded CodedInputStream to FlowControlRequest"
  [is]
  (serdes.core/cis->embedded cis->FlowControlRequest is))

(defn new-FlowControlRequest
  "Creates a new instance from a map, similar to map->FlowControlRequest except that
  it properly accounts for nested messages, when applicable.
  "
  [init]
  {:pre [(if (s/valid? ::FlowControlRequest-spec init) true (throw (ex-info "Invalid input" (s/explain-data ::FlowControlRequest-spec init))))]}
  (-> (merge FlowControlRequest-defaults init)
      (map->FlowControlRequest-record)))

(defn pb->FlowControlRequest
  "Protobuf to FlowControlRequest"
  [input]
  (cis->FlowControlRequest (serdes.stream/new-cis input)))

(def ^:protojure.protobuf.any/record FlowControlRequest-meta {:type "protojure.test.grpc.FlowControlRequest" :decoder pb->FlowControlRequest})

;-----------------------------------------------------------------------------
; FlowControlPayload
;-----------------------------------------------------------------------------
(defrecord FlowControlPayload-record [id data]
  pb/Writer
  (serialize [this os]
    (serdes.core/write-Int32 1  {:optimize true} (:id this) os)
    (serdes.core/write-Bytes 2  {:optimize true} (:data this) os))
  pb/TypeReflection
  (gettype [this]
    "protojure.test.grpc.FlowControlPayload"))

(s/def :protojure.test.grpc.FlowControlPayload/id int?)
(s/def :protojure.test.grpc.FlowControlPayload/data bytes?)
(s/def ::FlowControlPayload-spec (s/keys :opt-un [:protojure.test.grpc.FlowControlPayload/id :protojure.test.grpc.FlowControlPayload/data ]))
(def FlowControlPayload-defaults {:id 0 :data (byte-array 0) })

(defn cis->FlowControlPayload
  "CodedInputStream to FlowControlPayload"
  [is]
  (->> (tag-map FlowControlPayload-defaults
         (fn [tag index]
             (case index
               1 [:id (serdes.core/cis->Int32 is)]
               2 [:data (serdes.core/cis->Bytes is)]

               [index (serdes.core/cis->undefined tag is)]))
         is)
        (map->FlowControlPayload-record)))

(defn ecis->FlowControlPayload
  "Embedded CodedInputStream to FlowControlPayload"
  [is]
  (serdes.core/cis->embedded cis->FlowControlPayload is))

(defn new-FlowControlPayload
  "Creates a new instance from a map, similar to map->FlowControlPayload except that
  it properly accounts for nested messages, when applicable.
  "
  [init]
  {:pre [(if (s/valid? ::FlowControlPayload-spec init) true (throw (ex-info "Invalid input" (s/explain-data ::FlowControlPayload-spec init))))]}
  (-> (merge FlowControlPayload-defaults init)
      (map->FlowControlPayload-record)))

(defn pb->FlowControlPayload
  "Protobuf to FlowControlPayload"
  [input]
  (cis->FlowControlPayload (serdes.stream/new-cis input)))

(def ^:protojure.protobuf.any/record FlowControlPayload-meta {:type "protojure.test.grpc.FlowControlPayload" :decoder pb->FlowControlPayload})

;-----------------------------------------------------------------------------
; MetadataResponse
;-----------------------------------------------------------------------------
(defrecord MetadataResponse-record [msg]
  pb/Writer
  (serialize [this os]
    (serdes.core/write-String 1  {:optimize true} (:msg this) os))
  pb/TypeReflection
  (gettype [this]
    "protojure.test.grpc.MetadataResponse"))

(s/def :protojure.test.grpc.MetadataResponse/msg string?)
(s/def ::MetadataResponse-spec (s/keys :opt-un [:protojure.test.grpc.MetadataResponse/msg ]))
(def MetadataResponse-defaults {:msg "" })

(defn cis->MetadataResponse
  "CodedInputStream to MetadataResponse"
  [is]
  (->> (tag-map MetadataResponse-defaults
         (fn [tag index]
             (case index
               1 [:msg (serdes.core/cis->String is)]

               [index (serdes.core/cis->undefined tag is)]))
         is)
        (map->MetadataResponse-record)))

(defn ecis->MetadataResponse
  "Embedded CodedInputStream to MetadataResponse"
  [is]
  (serdes.core/cis->embedded cis->MetadataResponse is))

(defn new-MetadataResponse
  "Creates a new instance from a map, similar to map->MetadataResponse except that
  it properly accounts for nested messages, when applicable.
  "
  [init]
  {:pre [(if (s/valid? ::MetadataResponse-spec init) true (throw (ex-info "Invalid input" (s/explain-data ::MetadataResponse-spec init))))]}
  (-> (merge MetadataResponse-defaults init)
      (map->MetadataResponse-record)))

(defn pb->MetadataResponse
  "Protobuf to MetadataResponse"
  [input]
  (cis->MetadataResponse (serdes.stream/new-cis input)))

(def ^:protojure.protobuf.any/record MetadataResponse-meta {:type "protojure.test.grpc.MetadataResponse" :decoder pb->MetadataResponse})

