;;;----------------------------------------------------------------------------------
;;; Generated by protoc-gen-clojure.  DO NOT EDIT
;;;
;;; GRPC protojure.test.closedetect.CloseDetect Service Implementation
;;;----------------------------------------------------------------------------------
(ns protojure.test.closedetect.CloseDetect.server
  (:require [protojure.test.closedetect :refer :all]
            [com.google.protobuf :as com.google.protobuf]))

;-----------------------------------------------------------------------------
; GRPC CloseDetect
;-----------------------------------------------------------------------------
(defprotocol Service
  (Subscribe [this param]))

(defn- Subscribe-dispatch
  [ctx request]
  (Subscribe ctx request))

(def ^:const rpc-metadata
  [{:pkg "protojure.test.closedetect" :service "CloseDetect" :method "Subscribe" :method-fn Subscribe-dispatch :server-streaming true :client-streaming false :input pb->SubscribeRequest :output com.google.protobuf/new-Any}])
